# Generated by Django 4.2.30 on 2026-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedPaper',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=320)),
                ('authors', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=240)),
                ('year', models.PositiveSmallIntegerField()),
                ('topic', models.CharField(blank=True, max_length=180)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('to_read', 'To read'), ('reading', 'Reading'), ('read', 'Read'), ('ignored', 'Ignored'), ('important', 'Important')], default='recommended', max_length=20)),
                ('recommended_at', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=180)),
                ('arxiv_id', models.CharField(blank=True, max_length=120)),
                ('paper_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.ManyToManyField(blank=True, related_name='recommended_papers', to='documents.document')),
                ('tags', models.ManyToManyField(blank=True, related_name='recommended_papers', to='core.tag')),
            ],
            options={
                'ordering': ['-recommended_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='recommendedpaper',
            constraint=models.UniqueConstraint(condition=models.Q(('doi', ''), _negated=True), fields=('doi',), name='unique_recommended_paper_doi'),
        ),
        migrations.AddConstraint(
            model_name='recommendedpaper',
            constraint=models.UniqueConstraint(condition=models.Q(('arxiv_id', ''), _negated=True), fields=('arxiv_id',), name='unique_recommended_paper_arxiv'),
        ),
    ]
