import type { PublicNote } from './types'

export const publicNotes: PublicNote[] = [
  {
    id: 1,
    slug: 'towards-longitudinal-medical-image-generation',
    title: 'Towards Longitudinal Medical Image Generation',
    summary: 'Research notes on temporal consistency, uncertainty, and disease progression.',
    excerpt: 'A living research note on what it means to generate a plausible future scan: preserve patient identity, represent uncertainty, and make change clinically legible.',
    kind: 'Research Note',
    publishedAt: '2026-09-10',
    displayDate: '10 Sep 2026',
    readingTime: '8 min',
    tags: ['Longitudinal', 'Generation', 'MRI'],
    featured: true,
  },
  {
    id: 2,
    slug: 'evaluating-domain-generalization',
    title: 'Evaluating Domain Generalization Without Fooling Ourselves',
    summary: 'A practical argument for stronger splits, honest baselines, and uncertainty-aware reporting.',
    excerpt: 'Generalization claims are only as useful as the unseen domains used to test them. These are the evaluation choices I keep returning to.',
    kind: 'Essay',
    publishedAt: '2026-08-24',
    displayDate: '24 Aug 2026',
    readingTime: '6 min',
    tags: ['Domain Generalization', 'Evaluation'],
    featured: false,
  },
  {
    id: 3,
    slug: 'reproducible-monai-experiments',
    title: 'A Reproducible MONAI Experiment Setup',
    summary: 'Project layout, configuration boundaries, deterministic training, and experiment metadata.',
    excerpt: 'A maintained setup guide for turning a promising notebook into a repeatable medical imaging experiment.',
    kind: 'Guide',
    publishedAt: '2026-08-02',
    displayDate: '02 Aug 2026',
    readingTime: '12 min',
    tags: ['MONAI', 'PyTorch', 'Reproducibility'],
    featured: false,
  },
  {
    id: 4,
    slug: 'medical-image-generation-reading-map',
    title: 'Medical Image Generation — A Reading Map',
    summary: 'A structured index of diffusion, flow matching, evaluation, and clinical translation papers.',
    excerpt: 'Not a static bibliography, but a map organized around the questions each line of work is trying to answer.',
    kind: 'Reference',
    publishedAt: '2026-07-18',
    displayDate: '18 Jul 2026',
    readingTime: 'Living document',
    tags: ['Reading List', 'Diffusion', 'Evaluation'],
    featured: false,
  },
  {
    id: 5,
    slug: 'temporal-consistency-metrics',
    title: 'Notes on Temporal Consistency Metrics',
    summary: 'What pixel, perceptual, anatomical, and clinical measures each fail to capture.',
    excerpt: 'A short comparison of metrics for evaluating generated longitudinal sequences and the assumptions hidden inside them.',
    kind: 'Research Note',
    publishedAt: '2026-06-29',
    displayDate: '29 Jun 2026',
    readingTime: '5 min',
    tags: ['Metrics', 'Temporal Modeling'],
    featured: false,
  },
]

