<script setup lang="ts">
import { computed, ref } from 'vue'
import DashboardPageHeader from '@/components/shared/DashboardPageHeader.vue'
import AppButton from '@/components/ui/AppButton.vue'
import TagEditor from '@/components/shared/TagEditor.vue'
import MediaEditor from '@/components/shared/MediaEditor.vue'
import { newId, useWorkspaceStore, normalizeTags, type ManagedPublication } from '@/stores/workspace'
const store = useWorkspaceStore(); const query = ref(''); const draft = ref<ManagedPublication | null>(null); const notice = ref(''); const confirmDelete = ref(false)
const records = computed(() => store.publications.filter(p => `${p.title} ${p.authors} ${p.tags.join(' ')}`.toLowerCase().includes(query.value.toLowerCase())).sort((a,b) => b.year - a.year))
function edit(p: ManagedPublication) { draft.value = JSON.parse(JSON.stringify(p)); notice.value = ''; confirmDelete.value = false }
function create() { draft.value = { id: newId(), title: '', authors: '', venue: '', venueShort: '', year: new Date().getFullYear(), type: 'Conference', tags: [], featured: false, motivation: '', approach: '', abstract: '', paperUrl: '', codeUrl: '', projectUrl: '', bibtex: '', mediaType: 'image', mediaUrl: '', mediaAlt: '', caption: '' }; notice.value = ''; confirmDelete.value = false }
async function save() { if (!draft.value?.title.trim()) { notice.value = 'Please enter a title.'; return }; const value = JSON.parse(JSON.stringify(draft.value)) as ManagedPublication; value.tags = normalizeTags(value.tags); value.image = value.mediaType === 'image' ? value.mediaUrl : ''; const saved = await store.savePublication(value); draft.value = JSON.parse(JSON.stringify(saved)); notice.value = 'Saved. Publications and homepage selected papers use this record.' }
async function remove() { if (!draft.value) return; await store.deletePublication(draft.value); draft.value = null; confirmDelete.value = false; notice.value = 'Publication removed. Its unused media remains in Settings until you delete it.' }
</script>
<template><div><DashboardPageHeader :title="$t('Publications')" :description="$t('Manage your authored papers, figures, methods and publication links.')"><RouterLink class="dashboard-preview-link" to="/publications">{{ $t("Preview publications ↗") }}</RouterLink><AppButton @click="create">{{ $t("Add publication") }}</AppButton></DashboardPageHeader><p v-if="notice" class="feedback" role="status">{{ $t(notice) }}</p><div class="manager-split"><section class="record-list"><input v-model="query" :aria-label="$t('Search publications')" :placeholder="$t('Search publications…')" /><button v-for="paper in records" :key="paper.id" class="record-row" :class="{ active: draft?.id === paper.id }" @click="edit(paper)"><strong>{{ paper.title }}</strong><small>{{ paper.year }} · {{ paper.venueShort || paper.type }}{{ paper.featured ? $t(' · Featured') : '' }}</small><span>{{ paper.tags.join(' · ') }}</span></button><p v-if="!records.length" class="empty-hint">{{ $t("No publications yet.") }}</p></section><section v-if="draft" class="record-editor"><form @submit.prevent="save"><div class="editor-heading"><h2>{{ $t("Publication details") }}</h2><AppButton type="submit">{{ $t("Save publication") }}</AppButton></div><label>{{ $t("Title") }}<input v-model="draft.title" required /></label><label>{{ $t("Authors") }}<input v-model="draft.authors" /></label><div class="field-grid"><label>{{ $t("Venue") }}<input v-model="draft.venue" /></label><label>{{ $t("Venue abbreviation") }}<input v-model="draft.venueShort" /></label><label>{{ $t("Year") }}<input v-model.number="draft.year" type="number" min="1900" max="2200" required /></label><label>{{ $t("Type") }}<select v-model="draft.type"><option value="Conference">{{ $t("Conference") }}</option><option value="Journal">{{ $t("Journal") }}</option><option value="Preprint">{{ $t("Preprint") }}</option></select></label></div><label>{{ $t("Motivation · one sentence") }}<textarea v-model="draft.motivation" rows="2" /></label><label>{{ $t("Approach · one sentence") }}<textarea v-model="draft.approach" rows="2" /></label><label>{{ $t("Abstract") }}<textarea v-model="draft.abstract" rows="4" /></label><TagEditor v-model="draft.tags" /><label class="check-field"><input v-model="draft.featured" type="checkbox" /> {{ $t("Show in homepage selected publications") }}</label>
          <p class="muted-copy">{{ $t("All selected publications appear on the homepage, newest year first.") }}</p><MediaEditor :model-value="draft" @update:model-value="value => Object.assign(draft!, value)" /><div class="field-grid"><label>{{ $t("Paper URL") }}<input v-model="draft.paperUrl" type="url" /></label><label>{{ $t("Code URL") }}<input v-model="draft.codeUrl" type="url" /></label><label>{{ $t("Project URL") }}<input v-model="draft.projectUrl" type="url" /></label></div><label>{{ $t("BibTeX") }}<textarea v-model="draft.bibtex" rows="5" /></label><div class="editor-actions"><AppButton type="submit">{{ $t("Save publication") }}</AppButton><button v-if="store.publications.some(p => p.id === draft?.id)" type="button" class="text-action danger" @click="confirmDelete = true">{{ $t("Delete publication") }}</button></div><div v-if="confirmDelete" class="inline-confirm"><span>{{ $t("Delete this publication record?") }}</span><AppButton @click="remove">{{ $t("Delete publication") }}</AppButton><button type="button" @click="confirmDelete = false">{{ $t("Cancel") }}</button></div></form></section><section v-else class="record-editor empty-state"><h2>{{ $t("Your published work") }}</h2><p>{{ $t("Select a publication or add one. Research projects and authored papers remain separate collections.") }}</p></section></div></div></template>
