export type PaperStatus = 'recommended' | 'to_read' | 'reading' | 'read' | 'ignored' | 'important'
export interface Paper { id: number; title: string; authors: string; venue: string; year: number; topic: string; tags: string[]; status: PaperStatus; recommendedAt: string; reason: string; abstract: string; rating?: number; doi?: string; arxivId?: string }
export const paperStatusMeta: Record<PaperStatus, { label: string; tone: 'neutral' | 'success' | 'warning' | 'info' }> = {
  recommended: { label: 'Recommended', tone: 'neutral' }, to_read: { label: 'To read', tone: 'info' }, reading: { label: 'Reading', tone: 'warning' }, read: { label: 'Read', tone: 'success' }, ignored: { label: 'Ignored', tone: 'neutral' }, important: { label: 'Important', tone: 'warning' },
}
export const papers: Paper[] = [
  { id: 31, title: 'MedMamba: Vision Mamba for Medical Image Classification', authors: 'Yue et al.', venue: 'arXiv', year: 2026, topic: 'Medical Image Analysis', tags: ['Mamba', 'Classification'], status: 'read', recommendedAt: 'Sep 08, 2026', reason: 'Useful backbone comparison for representation experiments.', abstract: 'A selective state-space architecture adapted to multi-scale medical image classification.', rating: 4, arxivId: '2403.03849' },
  { id: 30, title: 'Temporal Diffusion for Longitudinal Medical Image Synthesis', authors: 'Chen, Wang, Li et al.', venue: 'MICCAI', year: 2026, topic: 'Medical Image Generation', tags: ['Diffusion', 'Longitudinal', 'MRI'], status: 'important', recommendedAt: 'Sep 07, 2026', reason: 'Directly overlaps with temporal consistency and sparse visits.', abstract: 'A diffusion formulation for synthesizing future scans conditioned on irregular patient timelines.', rating: 5, doi: '10.1007/example.2026.31' },
  { id: 29, title: 'Do Domain Generalization Methods Generalize Well?', authors: 'Gulrajani & Lopez-Paz', venue: 'ICLR', year: 2021, topic: 'Domain Generalization', tags: ['Benchmark', 'OOD'], status: 'reading', recommendedAt: 'Sep 04, 2026', reason: 'Foundational benchmark methodology for evaluating DG claims.', abstract: 'A controlled study of domain generalization algorithms under consistent model selection.' },
  { id: 28, title: 'Latent Disease Trajectories from Sparse Clinical Imaging', authors: 'Park et al.', venue: 'TMI', year: 2025, topic: 'Disease Progression', tags: ['Trajectory', 'CT', 'Survival'], status: 'to_read', recommendedAt: 'Aug 29, 2026', reason: 'Connects time-to-event modeling with imaging representations.', abstract: 'Latent variable models align irregular clinical observations into disease progression trajectories.' },
  { id: 27, title: 'Segment Anything in Medical Images', authors: 'Ma et al.', venue: 'Nature Communications', year: 2024, topic: 'Medical Image Analysis', tags: ['Foundation Model', 'Segmentation'], status: 'read', recommendedAt: 'Aug 18, 2026', reason: 'Relevant foundation model baseline.', abstract: 'A promptable segmentation foundation model adapted across medical imaging modalities.', rating: 4 },
]

