# Generated by Django 4.2.30 on 2026-09-11 10:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentResearchItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('number', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=240)),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=80)),
                ('question', models.TextField(blank=True)),
                ('method', models.TextField(blank=True)),
                ('updated_label', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Syins Yibinory', max_length=120)),
                ('title', models.CharField(default='Medical imaging researcher', max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('headline', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('research_directions', models.TextField(blank=True)),
                ('featured_research_intro', models.TextField(blank=True)),
                ('current_research_heading', models.CharField(blank=True, max_length=240)),
                ('featured_research_heading', models.CharField(blank=True, max_length=240)),
                ('publications_heading', models.CharField(blank=True, max_length=240)),
                ('publications_description', models.TextField(blank=True)),
                ('notes_heading', models.CharField(blank=True, max_length=240)),
                ('notes_description', models.TextField(blank=True)),
                ('scholar_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('cv_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=240)),
                ('motivation', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=80)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('media_url', models.TextField(blank=True)),
                ('media_alt', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_projects', to='core.mediaasset')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
