# Generated by Django 4.2.30 on 2026-09-11 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=240)),
                ('venue_short', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('Conference', 'Conference'), ('Journal', 'Journal'), ('Preprint', 'Preprint')], default='Conference', max_length=20)),
                ('motivation', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('paper_url', models.URLField(blank=True)),
                ('code_url', models.URLField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('bibtex', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('media_type', models.CharField(default='image', max_length=20)),
                ('media_url', models.TextField(blank=True)),
                ('media_alt', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='core.mediaasset')),
                ('tags', models.ManyToManyField(blank=True, related_name='publications', to='core.tag')),
            ],
            options={
                'ordering': ['-year', '-id'],
            },
        ),
    ]
