# Generated by Django 4.2.30 on 2026-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('Research Note', 'Research Note'), ('Essay', 'Essay'), ('Guide', 'Guide'), ('Reference', 'Reference')], default='Research Note', max_length=30)),
                ('content', models.TextField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('reading_time', models.CharField(default='1 min', max_length=60)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('unlisted', 'Unlisted')], default='private', max_length=12)),
                ('featured', models.BooleanField(default=False)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='documents', to='core.tag')),
            ],
            options={
                'ordering': ['-published_at', '-updated_at', '-id'],
            },
        ),
    ]
