# Generated by Django 4.2.30 on 2026-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('hostname', models.CharField(blank=True, max_length=180)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('os', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='offline', max_length=12)),
                ('provider', models.CharField(choices=[('mock', 'Mock'), ('ssh', 'SSH'), ('xui', '3x-ui')], default='mock', max_length=12)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('uptime', models.CharField(blank=True, max_length=80)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('cpu', models.FloatField(default=0)),
                ('memory', models.JSONField(blank=True, default=dict)),
                ('disk', models.JSONField(blank=True, default=dict)),
                ('gpus', models.JSONField(blank=True, default=list)),
                ('containers', models.PositiveIntegerField(default=0)),
                ('connector_config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
    ]
