# Generated by Django 4.2.30 on 2026-09-11 17:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_percent', models.FloatField(default=0)),
                ('memory_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('memory_total_bytes', models.PositiveBigIntegerField(default=0)),
                ('disk_used_bytes', models.PositiveBigIntegerField(default=0)),
                ('disk_total_bytes', models.PositiveBigIntegerField(default=0)),
                ('gpu_utilization_percent', models.FloatField(blank=True, null=True)),
                ('gpu_memory_used_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gpu_memory_total_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('gpu_count', models.PositiveIntegerField(default=0)),
                ('containers', models.PositiveIntegerField(default=0)),
                ('load_average', models.FloatField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-recorded_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='server',
            name='encrypted_password',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='server',
            name='host_key_fingerprint',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='server',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveSmallIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='server',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['enabled', 'provider', 'status'], name='servers_ser_enabled_97e658_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['is_primary'], name='servers_ser_is_prim_ad9f8d_idx'),
        ),
        migrations.AddField(
            model_name='servermetricsample',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='servers.server'),
        ),
        migrations.AddIndex(
            model_name='servermetricsample',
            index=models.Index(fields=['server', '-recorded_at'], name='servers_ser_server__0f407f_idx'),
        ),
    ]
