# Generated by Django 4.2.30 on 2026-09-11 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_servermetricsample_server_encrypted_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
    ]
